Projeto_Itaú/urls.py
# coding=utf-8

"""Projeto_Itaú URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout

from Core import views
from catalog import views as views_catalog

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^Contato/$', views.contato, name='contato'),
    url(r'^Entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^Sair/$', logout, {'next_page': 'index'}, name='logout'),
    url(r'^Catalogo/', include('catalog.urls', namespace='catalog')),
    url(r'^Conta/', include('accounts.urls', namespace='accounts')),
    url(r'^Compras/', include('checkout.urls', namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

catalog/urls.py
# coding=utf-8


from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.product_list, name='product_list'),
	url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
	url(r'^produtos/(?P<slug>[\w_-]+)/$', views.produto, name='produto'),
]

checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
	url(
		r'^Carrinho/Adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem, 
		name='create_cartitem'
	),
	url(r'^Carrinho/$', views.cart_item, name='cart_item'),
	url(r'^finalizando/$', views.checkout, name='checkout'),
	url(r'^Histórico-de-Pedidos/$', views.order_list, name='order_list')
]

checkout/models.py
# coding=utf-8

from django.db import models
from django.conf import settings

from catalog.models import Product


class CartItemManager(models.Manager):

    def add_item(self, cart_key, product):
        if self.filter(cart_key=cart_key, product=product).exists():
            created = False
            cart_item = self.get(cart_key=cart_key, product=product)
            cart_item.quantity = cart_item.quantity + 1
            cart_item.save()
        else:
            created = True
            cart_item = CartItem.objects.create(
                cart_key=cart_key, product=product, price=product.price
            )
        return cart_item, created


class CartItem(models.Model):

    cart_key = models.CharField(
        'Chave do Carrinho', max_length=40, db_index=True
    )
    product = models.ForeignKey('catalog.Product', verbose_name='Produto')
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    objects = CartItemManager()

    class Meta:
    	verbose_name = 'Item do Carrinho'
    	verbose_name_plural = 'Itens dos Carrinhos'
    	unique_together = (('cart_key', 'product'),)

    def __str__(self):
    	return '{} [{}]'.format(self.product, self.quantity)


class OrderManager(models.Manager):

    def create_order(self, user, cart_items):
        order = self.create(user=user)
        for cart_item in cart_items:
            order_item = OrderItem.objects.create(
                order=order, quantity=cart_item.quantity, product=cart_item.product,
                price=cart_item.price
            )
        return order


class Order(models.Model):

    STATUS_CHOICES = (
        (0, 'Aguardando Pagamento'),
        (1, 'Concluída'),
        (2, 'Cancelada'),
    )

    PAYMENT_OPTION_CHOICES = (
    	('deposit', 'Depósito'),
        ('pagseguro', 'PagSeguro'),
        ('paypal', 'Paypal'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário')
    status = models.IntegerField(
        'Situação', choices=STATUS_CHOICES, default=0, blank=True
    )
    payment_option = models.CharField(
        'Opção de Pagamento', choices=PAYMENT_OPTION_CHOICES, max_length=20,
        default='deposit'
    )

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    objects = OrderManager()

    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __str__(self):
        return 'Pedido #{}'.format(self.pk)

    
    def product(self):
        product_ids = self.items.values_list('product')
        return Product.objects.filter(pk__in=product_ids)


class OrderItem(models.Model):

    order = models.ForeignKey(Order, verbose_name='Pedido', related_name='itens')
    product = models.ForeignKey('catalog.product', verbose_name='Produto')
    quantity = models.PositiveIntegerField('Quantidade', default=1)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens dos pedidos'

    def __str__(self):
        return '[{}] {}'.format(self.order, self.product)


def post_save_cart_item(instance, **kwargs):
    if instance.quantity < 1:
        instance.delete()


models.signals.post_save.connect(
   	post_save_cart_item, sender=CartItem, dispatch_uid='post_save_cart_item'
)


checkout/views.py
# coding=utf-8

from django.shortcuts import get_object_or_404, redirect
from django.views.generic import RedirectView, TemplateView, ListView
from django.forms import modelformset_factory
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.http import HttpResponse

from catalog.models import Product

from .models import CartItem, Order


class CreateCartItemView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        produto = get_object_or_404(Product, slug=self.kwargs['slug'])
        if self.request.session.session_key is None:
            self.request.session.save()
        cart_item, created = CartItem.objects.add_item(
            self.request.session.session_key, produto
        )
        if created:
            messages.success(self.request, 'Produto adicionado com sucesso')
        else:
            messages.success(self.request, 'Produto atualizado com sucesso')
        return reverse('checkout:cart_item')


class CartItemView(TemplateView):

    template_name = 'checkout/cart.html'

    def get_formset(self, clear=False):
    	CartItemFormSet = modelformset_factory(
    		CartItem, fields=('quantity',), can_delete=True, extra=0
    	)
    	session_key = self.request.session.session_key
    	if session_key:
    		if clear:
    			formset = CartItemFormSet(
    				queryset=CartItem.objects.filter(cart_key=session_key)
    		)
    		else:
    			formset = CartItemFormSet(
    				queryset=CartItem.objects.filter(cart_key=session_key),
    				data=self.request.POST or None
    			)
    	else:
    		formset = CartItemFormSet(queryset=CartItem.objects.none())
    	return formset


    def get_context_data(self, **kwargs):
    	context = super(CartItemView, self).get_context_data(**kwargs)
    	context['formset'] = self.get_formset()
    	return context


    def post(self, request, *args, **kwargs):
        formset = self.get_formset()
        context = self.get_context_data(**kwargs)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Carrinho atualizado com sucesso')
            context['formset'] = self.get_formset(clear=True)
        return self.render_to_response(context)


class CheckoutView(LoginRequiredMixin, TemplateView):

    template_name = 'checkout/checkout.html'

    def get(self, request, *args, **kwargs):
        session_key = request.session.session_key
        if session_key and CartItem.objects.filter(cart_key=session_key).exists():
            cart_items = CartItem.objects.filter(cart_key=session_key)
            order = Order.objects.create_order(
                user=request.user, cart_items=cart_items
            )
            cart_items.delete()
        else:
            messages.info(request, 'Não há itens no carrinho de compras')
            return redirect('checkout:cart_item')
        response = super(CheckoutView, self).get(request, *args, **kwargs)
        response.context_data['order'] = order
        return response


class OrderListView(LoginRequiredMixin, ListView):

    template_name = 'checkout/order_list.html'
    paginate_by = 10

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


create_cartitem = CreateCartItemView.as_view()
cart_item = CartItemView.as_view()
checkout = CheckoutView.as_view()
order_list = OrderListView.as_view()

checkout/templates/checkout/cart.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
Carrinho de Compras
{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Início</a></li>
  <li class="active">Carrinho de Compras</li>
</ol>
<div class="page-header">
    <h1>Carrinho de Compras</h1>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form class="" action="" method="post">
            {% csrf_token %}
            {{ formset.management_form }}
            <table class="table table-bordered">
                <thead>
                    <th>
                        ID
                    </th>
                    <th>
                        Nome
                    </th>
                    <th>
                        Preço
                    </th>
                    <th style="width: 10%;">
                        Quantidade
                    </th>
                    <th>

                    </th>
                </thead>
                <tbody>
                    {% for form in formset %}
                    <tr>
                        <td>
                            {{ form.instance.product.pk }}
                        </td>
                        <td>
                            {{ form.instance.product }}
                        </td>
                        <td>
                            R$ {{ form.instance.price|floatformat:"2" }}
                        </td>
                        <td>
                            {% render_field form.quantity class='form-control' %}
                        </td>
                        <td class="text-center">
                            <button value="on" type="submit" name="{{ form.DELETE.html_name }}" class="btn btn-danger btn-sm">remover</button>
                            {{ form.id }}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p class="text-right">
                <a href="{% url 'catalog:product_list' %}" class="pull-left btn btn-default">Continuar Compras</a>
                <button type="submit" class="btn btn-primary" name="button">Atualizar Carrinho</button></li>
                <a href="{% url 'checkout:checkout' %}" class="btn btn-success">Finalizar Compra</a>
            </p>
        </form>
    </div>
</div>
{% endblock %}

checkout/templates/checkout/checkout.html
{% extends "base.html" %}

{% block title %}
Finalizar Compra
{% endblock %}

{% block container %}
<ol class="breadcrumb">
  <li><a href="{% url 'index' %}">Início</a></li>
  <li><a href="{% url 'checkout:cart_item' %}">Carrinho de Compras</a></li>
  <li class="active">Finalizar Compra</li>
</ol>
<div class="page-header">
    <h1>Finalizar Compra</h1>
</div>
<div class="row">
    <div class="col-md-12">
        <p>
            Pedido #{{ order.pk }}
        </p>
    </div>
    <div class="col-md-8 col-md-offset-2">
        <div class="alert alert-success">
            Pedido realizado com sucesso, para realizar o pagamento faça o depósito na seguinte conta: Banco: Itaú Ag.: XXXX CC.: XXXXXX-X
        </div>
        <p>
            
        </p>
    </div>
</div>
{% endblock %}

checkout/templates/checkout/order_list.html
{% extends "accounts/index.html" %}

{% load pagination %}

{% block title %}
Histórico de Pedidos
{% endblock %}

{% block accounts_container %}
<h2>Histórico de Pedidos</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Produtos
            </th>
            <th>
                Situação
            </th>
            <th>
                Data
            </th>
        </tr>
    </thead>
    <tbody>
        {% for order in object_list %}
        <tr>
            <td>
                <a href="#">#{{ order.pk }}</a>
            </td>
            <td>
                {% for produto in order.produto %}
                {{ product.name }}{% if not forloop.last %}<br />{% endif %}
                {% endfor %}
            </td>
            <td>
                {{ order.get_status_display }}
            </td>
            <td>
                {{ order.created|date:"d/m/Y" }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% pagination request paginator page_obj %}
{% endblock %}