Projeto_Itaú/urls.py
# coding=utf-8

"""Projeto_Itaú URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout

from Core import views
from catalog import views as views_catalog

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^Contato/$', views.contato, name='contato'),
    url(r'^Entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^Sair/$', logout, {'next_page': 'index'}, name='logout'),
    url(r'^Catalogo/', include('catalog.urls', namespace='catalog')),
    url(r'^Conta/', include('accounts.urls', namespace='accounts')),
    url(r'^Compras/', include('checkout.urls', namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

accounts/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^Alterar-Dados$', views.update_user, name='update_user'),
	url(r'^Alterar-Senhas$', views.update_password, name='update_password'),
	url(r'^registro$', views.register, name='register'),
	
]

catalog/urls.py
# coding=utf-8


from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.product_list, name='product_list'),
	url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
	url(r'^produtos/(?P<slug>[\w_-]+)/$', views.produto, name='produto'),
]

checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
	url(
		r'^Carrinho/Adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem, 
		name='create_cartitem'
	),
	url(r'^Carrinho/$', views.cart_item, name='cart_item'),
	url(r'^finalizando/$', views.checkout, name='checkout'),
	url(r'^Histórico-de-Pedidos/$', views.order_list, name='order_list')
]

Core/models.py
# coding=utf-8

from django.db import models

# Create your models here.

Core/forms.py
# coding=utf-8

from django import forms
from django.core.mail import send_mail
from django.conf import settings


class ContatoForm(forms.Form):

    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())


    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome: {0}\nE-mail:{1}\n{2}'.format(name, email, message)
        send_mail(
            'Contato do Django E-Commerce', message, settings.DEFAULT_FROM_EMAIL,
            [settings.DEFAULT_FROM_EMAIL]
        )

Core/views.py
# coding=utf-8

from django.shortcuts import render
from django.http import HttpResponse
from django.core.mail import send_mail
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import View, TemplateView, CreateView
from django.contrib.auth import get_user_model
from django.contrib import messages

from .forms import ContatoForm

User = get_user_model()


class IndexView(TemplateView):
	
	template_name = 'index.html'

index = IndexView.as_view()
		

def contato(request):
	success = False
	form = ContatoForm(request.POST or None)
	if form.is_valid():
		form.send_mail()
		success = True
	else:
		form = ContatoForm()
	context = {
		'form': form,
		'success': success
	}
	return render(request, 'contato.html', context)


Core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
  <link rel="stylesheet" href="{% static 'assets/extra.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'index' %}" class="navbar-brand">Itaú Digital</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'catalog:product_list' %}">Produtos</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
               {% for category in categories %}
               <li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
               {% endfor %}
              </ul>
            </li>
			<li>
				<a href="{% url 'contato' %}">Contato</a>
			</li>
          </ul>
          <form class="navbar-form navbar-left" role="search" action="{% url 'catalog:product_list' %}">
            <div class="form-group">
              <input name="q" type="text" class="form-control" placeholder="Pesquisar..." />
            </div>
          </form>
          <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'checkout:cart_item' %}">Carrinho</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:index' %}">Conta</a></li>
            <li><a href="{% url 'logout' %}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Entrar</a></li>
            <li><a href="{% url 'accounts:register' %}">Registro</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
    <div class="container margin-top">
    {% block messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
    {% endfor %}
    {% endblock %}
		{% block container %}{% endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
			      <li><a href="">Início</a></li>
			      <li><a href="">Produtos</a></li>
			      <li><a href="">Contato</a></li>
			      <li><a href="">Termos e Privacidade</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

Core/templates/contato.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}

Contato | {{ block.super }}

{% endblock %}

{% block container %}

	<div class="page-header">
			<h1>Fale conosco</h1>
			{% if success %}
			<div class="alert alert-success">
				Mensagem enviada com sucesso.
			</div>
			{% endif %}
			<form class="form-horizontal" action="" method="post">
				{% csrf_token %}
				<fieldset>
					{% for field in form %}
					<div class="form-group{% if field.errors %} has-error{% endif %}">
				      <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
				      <div class="col-md-9">
				        {% render_field field class='form-control' %}
				        {% for error in field.errors %}
                		<span class="help-block">{{ error }}</span>
                		{% endfor %}
				      </div>
				    </div>
					{% endfor %}
					<div class="form-group">
				      <div class="col-md-9 col-md-offset-3">
				        <button type="submit" class="btn btn-primary">Enviar</button>
				      </div>
				    </div>
				</fieldset>
			</form>
		</div>

{% endblock %}



Core/templates/index.html
{% extends "base.html" %}


{% block container %}

<div class="jumbotron page-header">
  <h1>Itaú Digital</h1>
  <p>Sempre pensando no amanhã</p>
  <p><a class="btn btn-primary">Saiba mais</a></p>
</div>

{% endblock %}



Core/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Entrar | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error }}              
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.username class="form-control" %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                  <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.password class="form-control" %}
                    {% for error in form.password.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>  
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Entrar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

Core/templates/pagination.html
<div class="row">
    <div class="col-md-12">
        <nav>
            <ul class="pagination">
                {% for page in paginator.page_range %}
                <li{% if page_obj.number == page %} class="active"{% endif %}><a href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
                {% endfor %}
            </ul>
        </nav>
    </div>
</div>

Core/templates/produto.html
{% extends "base.html" %}

{% block title %}

Produto | {{ block.super }}

{% endblock %}

{% block container %}

<div class="page-header">
		  <h1>Página do Produto</h1>
		</div>
		<div class="row">
		  <div class="col-sm-4">
			  <a href="#" class="thumbnail">
				  <img src="http://placehold.it/350x250" alt="" />
			  </a>
		  </div>
		  <div class="col-sm-8">
			  <dl>
			  	<dt>Lorem ipsum:</dt>
				<dd>Lorem ipsum dolor sit amet</dd>
				<dt>Lorem ipsum:</dt>
				<dd>Lorem ipsum dolor sit amet</dd>
				<dt>Lorem ipsum:</dt>
				<dd>Lorem ipsum dolor sit amet</dd>
				<dt>Lorem ipsum:</dt>
				<dd>Lorem ipsum dolor sit amet</dd>
				<dt>Lorem ipsum:</dt>
				<dd>Lorem ipsum dolor sit amet</dd>
			  </dl>
		  </div>
		</div>

{% endblock %}



Core/templates/produto_lista.html
{% extends "base.html" %}

{% block title %}
    Lista de Produtos | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Produtos</h1>
</div>
<div class="row">
    {% for produto in produto_lista %}
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <a href="#">
                <img src="http://placehold.it/350x250" alt="" />
            </a>
            <div class="caption">
                <h3>{{ produto }}</h3>
                {{ produto.description|linebreaks }}
                <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

Core/templates/produto_lista_old.html
{% extends "base.html" %}

{% block title %}
    Lista de Produtos | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Produtos</h1>
</div>
<div class="row">
    {% for produto in produto_lista %}
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <a href="#">
                <img src="http://placehold.it/350x250" alt="" />
            </a>
            <div class="caption">
                <h3>{{ produto }}</h3>
                {{ produto.description|linebreaks }}
                <p><a href="#" class="btn btn-success" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}