Projeto_Itaú/urls.py
# coding=utf-8

"""Projeto_Itaú URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout

from Core import views
from catalog import views as views_catalog

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^Contato/$', views.contato, name='contato'),
    url(r'^Entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^Sair/$', logout, {'next_page': 'index'}, name='logout'),
    url(r'^Catalogo/', include('catalog.urls', namespace='catalog')),
    url(r'^Conta/', include('accounts.urls', namespace='accounts')),
    url(r'^Compras/', include('checkout.urls', namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

catalog/urls.py
# coding=utf-8


from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.product_list, name='product_list'),
	url(r'^(?P<slug>[\w_-]+)/$', views.category, name='category'),
	url(r'^produtos/(?P<slug>[\w_-]+)/$', views.produto, name='produto'),
]

checkout/urls.py
# coding=utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
	url(
		r'^Carrinho/Adicionar/(?P<slug>[\w_-]+)/$', views.create_cartitem, 
		name='create_cartitem'
	),
	url(r'^Carrinho/$', views.cart_item, name='cart_item'),
	url(r'^finalizando/$', views.checkout, name='checkout'),
	url(r'^Histórico-de-Pedidos/$', views.order_list, name='order_list')
]

catalog/models.py
# coding=utf-8

from django.db import models
from django.core.urlresolvers import reverse


class Category(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug': self.slug})

class Product(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Identificador', max_length=100)
    category = models.ForeignKey('catalog.Category', on_delete=models.CASCADE,)
    #category = models.ForeignKey('catalog.Category', verbose_name='Categoria')
    description = models.TextField('Descrição', blank=True)
    price = models.DecimalField('Preço', decimal_places=2, max_digits=8)
    image = models.ImageField(
        'Imagem', upload_to='products', blank=True, null=True
    )

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:produto', kwargs={'slug': self.slug})

catalog/views.py
# coding=utf-8

from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.db import models

from .models import Product, Category


class ProductListView(generic.ListView):
    
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'
    paginate_by = 3

    def get_queryset(self):
        queryset = Product.objects.all()
        q = self.request.GET.get('q', '')
        if q:
            queryset = queryset.filter(
                models.Q(name__icontains=q) | models.Q(category__name__icontains=q) \
                | models.Q(description__icontains=q) | models.Q(price__icontains=q)
            )
        return queryset

        
class CategoryListView(generic.ListView):
    
    template_name = 'catalog/category.html'
    context_object_name = 'product_list'
    paginate_by = 3

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return context


def produto(request, slug):
    produto = Product.objects.get(slug=slug)
    context = {
        'produto': produto
    }
    return render(request, 'catalog/produto.html', context)


product_list = ProductListView.as_view()

category = CategoryListView.as_view()

catalog/templates/catalog/_produto.html
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <a href="{{ produto.get_absolute_url }}">
            {% if produto.image %}
            <img src="{{ produto.image.url }}" alt="" />
            {% else %}
            <img src="http://placehold.it/350x250" alt="" />
            {% endif %}
        </a>
        <div class="caption">
            <h3>{{ produto }}</h3>
            {{ produto.description|linebreaks }}
            <p><a href="{{ produto.get_absolute_url }}" class="btn btn-success" role="button">Detalhes</a> <a href="{% url 'checkout:create_cartitem' produto.slug %}" class="btn btn-default" role="button">Adicionar</a></p>
        </div>
    </div>
</div>

catalog/templates/catalog/category.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
    {{ current_category }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>{{ current_category }}</h1>
</div>
<div class="row">
    {% for produto in product_list %}
    {% include "catalog/_produto.html" %}
    {% endfor %}
</div>
{% pagination request paginator page_obj %}
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends "base.html" %}

{% load pagination %}

{% block title %}
    Lista de Produtos | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Produtos</h1>
</div>
<div class="row">
    {% for produto in products %}
    {% include "catalog/_produto.html" %}
    {% endfor %}
</div>
{% pagination request paginator page_obj %}
{% endblock %}

catalog/templates/catalog/produto.html
{% extends "base.html" %}

{% block title %}
	{{ Produto }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
	<h1>{{ produto }}</h1>
</div>
<div class="row">
	<div class="col-sm-4">
			<a href="{{ produto.get_absolute_url }}">
            	{% if produto.image %}
            	<img src="{{ produto.image.url }}" alt="" />
            	{% else %}
            	<img src="http://placehold.it/350x250" alt="" />
            	{% endif %}
        	</a>
	</div>
	<div class="col-sm-8">
		<p class="text-right">
			<a href="{% url 'checkout:create_cartitem' produto.slug %}" class="btn btn-success">Adicionar ao Carrinho</a>
		</p>
		{{ produto.description|linebreaks }}
        R$ {{ price.description|linebreaks }}
    </div>
</div>
{% endblock %}

